[advanced]
fnSeedAddr     = "0x5A1B2C3D"
fnChecksumAddr = "0x004010F0"
fnSendAddr     = "0x00ABCDEF"
fnRecvAddr     = "0x00ABCD01"

[logging]
showConsole     = true
saveLog         = true
saveSocketLog   = true
logsDir         = "logs"
appLogFilename  = "relay_app.log"
socketLogFilename = "relay_socket.log"

[kore]
host  = "127.0.0.1"
ports = [5293, 5294, 5295]

[kore.reconnect]
initial_ms = 500        # first break
max_ms     = 30000      # roof
backoff    = 2.0        # multiplier
jitter_p   = 0.2        # 20% jitter