[general]
showConsole   = true
saveLog       = true
saveSocketLog = true

[advanced]
fnSeedAddr     = "0x5A1B2C3D"
fnChecksumAddr = "0x004010F0"
fnSendAddr     = "0x00ABCDEF"
fnRecvAddr     = "0x00ABCD01"

[logging]
dir    = "logs"
app    = "relay_app.log"
socket = "relay_socket.log"

[kore1]
host = "127.0.0.1"
port = 2350